---
title: "How global climate change is reshaping our granary?"
---

As the Earth's temperature slowly rises, we are not only facing disappearing glaciers, rising sea levels and an increase in extreme weather events - our food security is also being threatened as never before. The impacts of global warming on agriculture are far-reaching and complex, and from shifts in planting seasons to adjustments in crop growth cycles, climate change is rewriting the global food production map.

But this story is not a one-dimensional pessimistic narrative. It is a story of challenge, opportunityand innovation. It involves scientists, farmers, policymakers and ordinary citizens, each working to address this global challenge. Through three interactive charts - showing changes in global temperature trends, population growth, and food production - we'll take you on a deep dive into how global warming is affecting our "breadbasket," and what we can do about it.

## Global Temperature Trends

According to the Food and Agriculture Organization of the United Nations (FAO), global climate change has both indirect and direct impacts on agrifood systems. Changes in rainfall patterns, the increased frequency of extreme weather events and phenomena such as ocean acidification directly threaten global food production and security. These changes are forcing agricultural producers to adapt to new environmental conditions, which often requires time and resources, and in some cases a complete reconfiguration of existing agricultural technologies and methods.

```{=html}
<iframe height="450" width="100%" frameborder="no" src="https://jinwchao.shinyapps.io/personal_app/"> </iframe>
```


The first graphic shows the effects of temperature trends on a global scale.

With the horizontal axis, we follow the march of time from the Industrial Revolution in the 19th century to the present day. The vertical axis, on the other hand, presents us with a reality that can't be ignored - rising average global temperatures. And the drop-down bar next to the chart, which allows us to select different countries, reveals a key truth: Global warming is a global problem, it affects different countries to different degrees.

This graph is a look back at the history of climate change over the past few centuries, but also a foretaste of what is to come. By looking at these temperature trends, we can begin to understand the impact that global warming may have on our "breadbasket" - global food production.

## Increasing world population

In the current study, Impacts of land use, population, and climate change on global food security, it is projected that the global population will peak at 9.7 billion in 2050, accompanied by a significant increase in demand for food. This population growth will inevitably put enormous pressure on the global food supply system. At the same time, frequent and extreme weather events triggered by climate change are eroding the stability and predictability of agricultural production, leading to reduced crop yields. Together, these factors constitute a major challenge to achieving food security on a global scale.

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://jinwchao.shinyapps.io/app-2/"> </iframe>
```


This visual window provides an interactive world map view of population growth and population density for different countries. The user selects the year (every decade from 1970 to 2020) via a slider, and the map then displays the population data for each country for that year. Each country is represented by a circle on the map, which changes in size and color to reflect the size and density of the population.

## Crop population over world

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://jinwchao.shinyapps.io/app-3/"> </iframe>
```


